version: "2.0"
services:
  fileserver:
    image: busybox:latest
    command: ["sh", "-c", "while true; do sleep 3600; done"]
    ports:
      - 80:80 # Not used in this simplified example
    volumes:
      - data:
          mountPath: /data
    persistentVolumes:
      data:
        size: "1Gi"
        class: default
